### ISSUE TITLE
Bot not working after the Channel Categories update

### ISSUE THREAD

**Issue by rolyd90** [WalshyDev/AutoCleanBot#2]
Created a empty/new discord, and bot will not work with Channel Categories. Would be nice to use this on my gaming server discord.

Thanks for looking.

```
[06:47:30] [Info] [JDA]: Login Successful!
[06:47:30] [Info] [JDASocket]: Connected to WebSocket
[06:47:30] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"name":"Text Channels","bitrate":64000,"position":0,"id":"407630224260464641","user_limit":0,"type":4}
[06:47:30] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"name":"Voice Channels","bitrate":64000,"position":0,"id":"407630224260464643","user_limit":0,"type":4}
[06:47:30] [Fatal] [JDASocket]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[],"name":"Text Channels","bitrate":64000,"position":0,"id":"407630224260464641","user_limit":0,"type":4}
[06:47:30] [Fatal] [JDASocket]: Encountered an exception:
[06:47:30] [Fatal] [JDASocket]: java.lang.RuntimeException: Got permission_override for unknown channel with id: 407630224260464641
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildChannelPass(EntityBuilder.java:398)
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:285)
        at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:38)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:814)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:517)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:848)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by WalshyDev** [comment]
Sorry for the late reply, I have pushed a fix. Download it here: https://github.com/WalshyDev/AutoCleanBot/releases/tag/v1 or at Dropbox here: https://www.dropbox.com/s/zwp10dbdfbcwqj0/AutoCleanBot.zip?dl=0
