### ISSUE TITLE
MySQL Unable to load authentication plugin 'caching_sha2_password'

### ISSUE THREAD

**Issue by abanksss** [WalshyDev/AutoCleanBot#8]
When I launched the bot it loaded properly but then I got this. I saw a similar issue from a while back but I think there are some differences so I'm making a new one. 

```
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:550)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:537)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:527)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:512)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:480)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:498)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:494)
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:1705)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1629)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:637)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:351)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:224)
        at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:418)
        at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:138)
        at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:109)
        at com.walshydev.jba.SQLController.getConnection(SQLController.java:20)
        at com.walshydev.jba.SQLController.runSqlTask(SQLController.java:24)
        at com.walshydev.autocleanbot.AutoCleanBot.scheduleCleans(AutoCleanBot.java:48)
        at com.walshydev.autocleanbot.AutoCleanBot.run(AutoCleanBot.java:43)
        at com.walshydev.jba.JBAListener.onReady(JBAListener.java:27)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:356)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.dv8tion.jda.core.requests.WebSocketClient.ready(WebSocketClient.java:202)
        at net.dv8tion.jda.core.handle.ReadyHandler.guildLoadComplete(ReadyHandler.java:166)
        at net.dv8tion.jda.core.handle.ReadyHandler.handleInternally(ReadyHandler.java:108)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:1035)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:691)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1099)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: com.mysql.cj.core.exceptions.WrongArgumentException: Unable to load authentication plugin 'caching_sha2_password'.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
        at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
        at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(MysqlaAuthenticationProvider.java:564)
        at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.connect(MysqlaAuthenticationProvider.java:204)
        at com.mysql.cj.mysqla.io.MysqlaProtocol.connect(MysqlaProtocol.java:1361)
        at com.mysql.cj.mysqla.MysqlaSession.connect(MysqlaSession.java:132)
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:1647)
        ... 28 more
01:35:46.266 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.core.requests.WebSocketClient - Resending 0 cached events...
01:35:46.267 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.core.requests.WebSocketClient - Sending of cached events finished.
```

**Comment by WalshyDev** [comment]
Please refer to [this StackOverflow answer](
https://stackoverflow.com/a/50433762/4833844)

**Comment by abanksss** [comment]
I'm sorry if my lack of knowledge in this is annoying. I have fixed that error using the link you gave me but now I'm getting this error:

Caused by: java.sql.SQLException: Unknown system variable 'query_cache_size'

(I don't really know if I'm supposed to make a new issue so I will move it to another if you tell me to)

**Comment by Redeyeback** [comment]
> Please refer to [this StackOverflow answer](https://stackoverflow.com/a/50433762/4833844)

I also am at this point and now receiving::
Caused by: java.sql.SQLException: Unknown system variable 'query_cache_size'
